### ISSUE TITLE
Are there weights available online for uniform soup model?

### ISSUE THREAD

**Issue by 25icecreamflavors** [mlfoundations/model-soups#1]
Hello, I wanted to use a model that was constructed with uniform weights, is it available online (I didn't find) or I need to download all models and construct it myself?

**Comment by mitchellnw** [comment]
Currently you have to download all the weights and construct it. While we do have code for this, I understand that this is not optimal. I'll try to find time to soon upload the uniform soup weights.

**Comment by mitchellnw** [comment]
The weights are now uploaded here: https://drive.google.com/file/d/1W4QvXCj2E3E6hd9u15861crlzqNTX2cJ/view?usp=sharing
