### ISSUE TITLE
Possible to provide minimal code for Figure 2?

### ISSUE THREAD

**Issue by sayakpaul** [mlfoundations/model-soups#3]
Thanks for the awesome paper! 

Is it possible to provide minimal code for reproducing some parts of Figure 2? I believe that would greatly benefit the community of researchers that are working on similar things.

**Comment by mitchellnw** [comment]
As we say in the fig caption, we follow the great work of Garipov et al., 2018 in creating this figure. Their repository is here: https://github.com/timgaripov/dnn-mode-connectivity with `plane.py` and `plane_plot.py` being the important files.

**Comment by sayakpaul** [comment]
Thanks.
