### ISSUE TITLE
checkpoint for ViT-g/14

### ISSUE THREAD

**Issue by sorobedio** [mlfoundations/model-soups#9]
Where to get the checkpoints of vit-g/14 models?
In the code i only saw code for VIT-B/32 base. could you show me how to load the ViT-G/14?

**Comment by mitchellnw** [comment]
The ViT-G/14 models are from https://arxiv.org/abs/2106.04560 and not available publicly.

There are open source efforts trying to train public ViT-G/14 zero-shot models, https://laion.ai/blog/giant-openclip/, but these models came after the soups paper so we did use them.

**Comment by sorobedio** [comment]
ok thank you
